### ISSUE TITLE
support remote validation

### ISSUE THREAD

**Issue by jarrettmeyer** [mustardamus/ketchup-plugin#1]
Could ketchup support remote validation? If a JSON "true" is returned, then accept the value.

```
$.fn.ketchup.validation('remote', function(element, url, testValue) {
  $.get(url, { x: testValue }, function(json) {
    return (json == true);
  });
});
```

I'd made a fork, but my repository is offline for backups right now.

**Comment by jarrettmeyer** [comment]
I've created a patch, adding both the validation and the message. Where can I send that?

**Comment by mustardamus** [comment]
Thanks Jarrett, it's in the Fork Queue. I'll check it out soon and merge it (I'm switching my ISP currently).

**Comment by mustardamus** [comment]
Closed in favor of the new version.
