### ISSUE TITLE
Whitespace validation

### ISSUE THREAD

**Issue by ertaius** [mustardamus/ketchup-plugin#10]
In the about you portion of the demo, one can enter more than ten spaces. maybe multiple (3+) &nbsp could be filtered out of the count?

**Comment by mustardamus** [comment]
Yes this isn't checked in the basic length validations, but that's the joy of Ketchup, you could add it easily. For example you could trim the value with [$.trim](http://jqapi.com/#p=jQuery.trim) the value before checking the length.
