### ISSUE TITLE
How to bypass validation on non-required fields

### ISSUE THREAD

**Issue by franck-grenier** [mustardamus/ketchup-plugin#11]
I put validation rules on non-required fields. When these fields are empty, I cannot submit the form.

Is it a Ketchup standard behaviour ?

**Comment by galdomedia** [comment]
I got rid of this problem in my branch of ketchup, unfortunately not yet merged into main repo.
http://github.com/galdomedia/ketchup-plugin/

**Comment by mustardamus** [comment]
Closed in favor of the new version.
