### ISSUE TITLE
Problem with position relative

### ISSUE THREAD

**Issue by benlagoutte** [mustardamus/ketchup-plugin#12]
Hi,

I've noticed an issue with ketchup (and worked out a fix). 

The position of the the error box is wrong if any parent in the hierarchy of the text field is set to position:relative, because the absolute positioning will be calculated from there.

Also using the errorContainer height in initialPositionContainer doesn't really work as the error labels inside it haven't been built.

Here's my patch for it. Works with both position:relative or not.

```
diff --git a/js/jquery.ketchup.js b/js/jquery.ketchup.js
index 8e31d2e..0be084a 100644
--- a/js/jquery.ketchup.js
+++ b/js/jquery.ketchup.js
@@ -204,17 +204,41 @@

   var initialPositionContainer = function(errorContainer, field) {
     var fOffset = field.offset();
+   var left = fOffset.left;
+   var top = fOffset.top;
+   
+   // check if there's a 'relative' parent
+   field.parents().each(function(){
+       if ($(this).css('position')=='relative')
+       {
+           fOffset = $(this).offset();
+           
+           left -= fOffset.left;
+           top -= fOffset.top;
+           
+           return false
+           
+       }
+       
+   });
+
+   // back it up for later 
+   field.data('offset',{left:left,top:top});

     errorContainer.css({
-      left: fOffset.left + field.width() - 10,
-      top: fOffset.top - errorContainer.height()
+      left: left + field.width() - 10,
+      top: top
     });
   };


   var positionContainer = function(errorContainer, field) {
+   // re-position the error, the height is correct here.
+   errorContainer.css({top:field.data('offset').top - errorContainer.height() + field.innerHeight()});
+   
+   // animate
     errorContainer.animate({
-      top: field.offset().top - errorContainer.height()
+      top: field.data('offset').top - errorContainer.height()
     });
   };
```

Cheers

**Comment by burnoski** [comment]
Hello !
What should i do to get this to work ?
Just copy/past it at the end of ketchup.js ?

Thx

**Comment by benlagoutte** [comment]
It's a patch, apply it with git (google apply git patch)

**Comment by burnoski** [comment]
Thank you !
After STFW i found how to do it... What a noob i am :)

**Comment by Tuckie** [comment]
fyi, this patch is also useful for absolute positioning. I changed:
if ($(this).css('position')=='relative')
to:
 if ($(this).css('position')=='relative' || $(this).css('position')=='absolute')

and it works great!

**Comment by mustardamus** [comment]
In the new version you can insert/position your error-container wherever you want :) Closed in favor of the new version.
