### ISSUE TITLE
Position issue on hidden form

### ISSUE THREAD

**Issue by kaycorbett** [mustardamus/ketchup-plugin#13]
I have a form that is hidden until a calender date is clicked. When the ketchup plugin gets called, the positioning is not correct, from the left anyway. The bubble appears to the far left of the screen. However, it will jump to the correct place after a few seconds. Is there a fix for this?

I am using Firefox 3.

Example here - http://www.longbarnshelve.co.uk/availability.php

**Comment by mustardamus** [comment]
Closed in favor of the new version.
