### ISSUE TITLE
Does not work with google jquery

### ISSUE THREAD

**Issue by shinokada** [mustardamus/ketchup-plugin#14]
Instead of js/jquery.min.js, I used http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js.

However it does not work with this.

**Comment by mcburden** [comment]
I am also having this issue.  Any solutions out there?

**Comment by frostbytten** [comment]
It will work if you don't use the jquery.ketchup.basic.min.js (use the full three files).

**Comment by mustardamus** [comment]
Closed in favor of the new version.
