### ISSUE TITLE
Scroll to first ketchup on submit

### ISSUE THREAD

**Issue by eduardoromero** [mustardamus/ketchup-plugin#15]
Hi Folks

I edited jquery.ketchup.js so it focus the frist ketchup-error-container when there's an error on submit, looks like this now:

around line 38:

```
  if(!tasty){
        //get the top offset of the target anchor
        var target_offset = $('div.ketchup-error-container:visible:first').offset();
        var target_top = target_offset.top - 30;

        //goto that anchor by setting the body scroll top to anchor top
        $('html, body').animate({scrollTop:target_top}, 500);
      return false;
  };
```

There may be a better way to do this :) but that's what I got ;)

Hope it helps somebody.

**Comment by racl101** [comment]
Thanks eduardoromero it was useful to me. You saved me some time.

**Comment by olivoil** [comment]
+1 
Thanks!

**Comment by mustardamus** [comment]
Kewl! Closed in favor of the new version.
