### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by burnoski** [mustardamus/ketchup-plugin#17]
Hello !

I have translated messages in french :

  'required':     'Ce champ est obligatoire',

  'minlength':    'Ce champ doit avoir une taille minimale de $arg1.',

  'maxlength':    'Ce champ doit avoir une taille maximale de $arg1.',

  'rangelength':  'Ce champ doit avoir une taille comprise entre $arg1 et $arg2.',

  'min':          'Doit contenir au moins $arg1.',

  'max':          'Ne peut pas être plus grand que $arg1.',

  'range':        'Doit être compris entre $arg1 et $arg2.',

  'number':       'Vous devez indiquer un nombre',

  'digits':       'Vous devez indiquer un chiffre',

  'email':        'Vous devez indiquer un email valide',

  'url':          'Vous devez indique une URL valide',

  'username':     'Vous devez indiquer un login valide',

  'match':        'Doit correspondre au champ ci-dessus',

  'date':         'Vous devez indiquer une date valide',

  'minselect':    'Sélectionner au moins $arg1 cases à cocher.',

  'maxselect':    'Ne pas sélectionner plus de $arg1 cases à cocher.',

  'rangeselect':  'Sélectionner de $arg1 à $arg2 cases à cocher.'

Have fun with ketchup...

**Comment by mustardamus** [comment]
Great, thanks! Translation files are planned for the new version. Closed in favor of the new version.
