### ISSUE TITLE
Validation For AJAX Forms

### ISSUE THREAD

**Issue by maubarra** [mustardamus/ketchup-plugin#18]
Hi, I'm trying to use Ketchup to validate some forms but in my case I never "submit" the forms, I call a function that sends an AJAX request to do the work.

Is there any way to "trigger" the validation and get a "true" (no errors) or "false" (errors) without submiting?

Thanks in advance and keep up the good work!

**Comment by mustardamus** [comment]
I'll write up some ajax example for the new version. Closed in favor of the new version.
