### ISSUE TITLE
Possible to validate a SELECT?

### ISSUE THREAD

**Issue by danielwilliampeters** [mustardamus/ketchup-plugin#19]
I can't find anywhere about validating a select (drop down list) with ketchup, I've tried but it doesn't work, anyone else done this?

**Comment by galdomedia** [comment]
How should such select be validated? For selected value different than given one?

**Comment by danielwilliampeters** [comment]
The default value (option) is a blank value. I need it to check its not blank, just like an input field validation with ketchup.

Any help he appreciated! =)

**Comment by galdomedia** [comment]
if you'll use &lt;option value=''&gt;Select value&lt;/option&gt; then 'required' validator should satisfy your needs. In other cases (ie. &lt;option&gt;Select value&lt;/option&gt;) use my fork of this repo (http://github.com/galdomedia/ketchup-plugin/) and validator 'notvalue'.

**Comment by danielwilliampeters** [comment]
I thought I tried value=""! Thank you for your help here. =)

**Comment by mustardamus** [comment]
Closed in favor of the new version.
