### ISSUE TITLE
error in position

### ISSUE THREAD

**Issue by rcheberle** [mustardamus/ketchup-plugin#20]
i have one error in position when I validade a form inside a div opened by blockUI ....
the code:

$("#btnID").bind("click",function()
{
   $.blockUI(
   {
      message: $("#form2"),
   });

   $("#form2").ketchup(
   {
     onSuccess: login,
     initialPositionContainer: function( errorContainer , field ){},
     positionContainer: function(errorContainer, field){}
  });
});

the buble appears below the field and not in the correct position.... some can help me?

**Comment by mustardamus** [comment]
Positioning is a lot easier in the new version. Closed in favor of the new version.
