### ISSUE TITLE
jquery conflicts

### ISSUE THREAD

**Issue by IndranilMutsuddy** [mustardamus/ketchup-plugin#21]
hello 
I am using jgrowl on the same page where i am trying to validate the fields at the same time now the problem is both are jquery and are mutually exclusive..what to do?
pleae help 
// For Jgrowl
    <script src="../jquery-1.3.2.js" type="text/javascript"></script>
    <script src="../jquery.jgrowl.js" type="text/javascript"></script>
    <link href="../jquery.jgrowl.css" rel="stylesheet" type="text/css" />
//For Ketchup
 <link href="../ketchup.jquery.ketchup.css" rel="stylesheet" type="text/css" />
            <script src="../JS/ketchup.jquery.min.js" type="text/javascript"></script>
            <script src="../JS/ketchup.jquery.ketchup.js" type="text/javascript"></script>
            <script src="../JS/ketchup.jquery.ketchup.messages.js" type="text/javascript"></script>
            <script src="../JS/ketchup.jquery.ketchup.validations.basic.js" type="text/javascript"></script>

```
        <script type ="text/javascript">
        $(document).ready(function() {
        $('#example1').ketchup();
        });
        </script>
```

**Comment by mustardamus** [comment]
Closed in favor of the new version.
