### ISSUE TITLE
Bug with a div in display:none resolved

### ISSUE THREAD

**Issue by nums** [mustardamus/ketchup-plugin#23]
If some input are in a div with a display:none; the error container is at the left of the window :
You have to put this line in the positionContainer : "left: fOffset.left + field.width() - 10,"

var positionContainer = function(errorContainer, field) {
    var fOffset = field.offset();
    errorContainer.animate({
    left: fOffset.left + field.width() - 10,
        top: field.offset().top - errorContainer.height()
    });
  };

**Comment by mustardamus** [comment]
Easier in the new version. Closed in favor of the new version.
