### ISSUE TITLE
Form Reset

### ISSUE THREAD

**Issue by damreywil** [mustardamus/ketchup-plugin#25]
What's the best way to hide all validation bubbles when a user clicks a form reset button?

TIA,
Damon

**Comment by damreywil** [comment]
no love?

**Comment by galdomedia** [comment]
i have this in my branch: http://github.com/galdomedia/ketchup-plugin
after reset reinitialize ketchup on form ($('form').ketchup();)

**Comment by mustardamus** [comment]
Yep, reinitializing works also in the new version. Closed in favor of the new version.
