### ISSUE TITLE
hide error container on click

### ISSUE THREAD

**Issue by regeda** [mustardamus/ketchup-plugin#3]
function bindField(field) {
...
    errorContainer.click( function () {
      hideContainer( $(this) );
      visibleContainer = false;
    });
...
}

**Comment by mustardamus** [comment]
Hmm, maybe this behavior should be in an extra callback defined by the user.

**Comment by regeda** [comment]
Maybe, yes!

**Comment by stephmoreau** [comment]
I've modified it a little so that the error container is the one who gets hidden once the element that has the error is seleceted!

```
field.click( function () {
        hideContainer( errorContainer );
        visibleContainer = false;
    });
```

**Comment by mustardamus** [comment]
Closed in favor of the new version.
