### ISSUE TITLE
minselect matches name, useless for checkboxes

### ISSUE THREAD

**Issue by ryanflorence** [mustardamus/ketchup-plugin#31]
If you've got:

```
<input type=checkbox name=one value="one"> One
<input type=checkbox name=one class="validates(minselect(1))" value="two"> Two
```

The validation works great, but it's useless.  When a user select both checkboxes only one value is passed to the sever, in this case "two" would be passed even though both are selected.  Checkboxes can't share the same name.

Currently I'm using a custom `data-group` attribute and using that in the validation.  I'm not settled on the best solution, but the current implementation is borked so I'm going with a data attribute.

An alternative I like is using `fieldset` and wrapping all the checkboxes into a fieldset and using that to find the checked elements.

**Comment by mustardamus** [comment]
I'll keep that in mind. Thanks. Closed in favor of the new version.
