### ISSUE TITLE
Need help, Would really be happy to get some help :) please.

### ISSUE THREAD

**Issue by samerbazzi** [mustardamus/ketchup-plugin#32]
I am using this with a 3rd part forms app, I have been able to integrate ketchup with live validation but I have the regular styles, I am trying to convert it to the pop-under style as shown here: 

Have it your way. Error-Container styling and behaviour. (  http://demos.usejquery.com/ketchup-plugin/yourway.html  )

Right now I use the normal styling as shown here: http://demos.usejquery.com/ketchup-plugin/yourway.html

Here is the code which I use along with my code: 

<link rel="stylesheet" type="text/css" media="screen" href="/form-lead-management/js/ketchup-plugin/css/jquery.ketchup.css" />

<script type="text/javascript" src="/form-lead-management/js/ketchup-plugin/js/jquery.ketchup.js"></script>

<script type="text/javascript" src="/form-lead-management/js/ketchup-plugin/js/jquery.ketchup.messages.js"></script>

<script type="text/javascript" src="/form-lead-management/js/ketchup-plugin/js/jquery.ketchup.validations.basic.js"></script>

<script type="text/javascript">
$(document).ready(function() {
  //add ketchup class to field
  
    //name
    $('#form_3 input#element_2_1').addClass("validate(required)");
    $('#form_3 input#element_2_2').addClass("validate(required)");
    $('#form_3 input#element_2_3').addClass("validate(required)");
    $('#form_3 input#element_2_4').addClass("validate(required)");

    //phone
    $('#form_3 input#element_1_1').addClass("validate(required)");
    $('#form_3 input#element_1_2').addClass("validate(required)");
    $('#form_3 input#element_1_3').addClass("validate(required)");
    
    //email
    $('#form_3 input#element_3').addClass("aaaaaaaaaaaaaaaaa");
    
    //city
    $('#form_3 input#element_5').addClass("validate(required)");
    
    //service
    $('#form_3 input#element_4').addClass("validate(required)");

    $('#form_3').ketchup();

});
</script>

My question is, how would I make it work with the new validation as shown here Have it your way. Error-Container styling and behaviour. (  http://demos.usejquery.com/ketchup-plugin/yourway.html  )

I tried to tweak and make changes but I just could not get it to work, any help would be great,

Thank you guys and amazing work!

Samer

**Comment by samerbazzi** [comment]
Sorry some of my code did not show up, basically is it possible to call a message box ob submit with the errors rather than the highlights and such? I tried to make the errors show up under the text areas but I had no luck with integration, I am a newbie with css and I still learning but I know how to put things together for now :)

**Comment by samerbazzi** [comment]
This is how I call it now per form element, how would I make it so it will show a popup box when it is sumbitted or show the style so it shows under the text area like it shows on the example ketchup website: 

$ ( ' # f o r m _ 3   i n  p u t # e l em e n t _ 2 _ 1 ' ) . a dd C l a s s ( "v a l i d a t e( r e qu i r e d ) " ) 

I had to reformat above because of the comments system here will remove code.

It would be great if someone can help,

-Sam

**Comment by mustardamus** [comment]
See if you can resolve it with the new version. Closed in favor of the new version.

P.S. You can use markdown in comments to describe code: http://daringfireball.net/projects/markdown/syntax
