### ISSUE TITLE
Pointer / Arrow is disconnected from Error Message

### ISSUE THREAD

**Issue by compumatter** [mustardamus/ketchup-plugin#33]
I have installed and tested this plugin. I like its potential very much. Thank you.

However, in all browsers I am getting a pointer that is disconnected from its container.

See this image: http://compumatter.com/test/validator/error.jpg

Your thoughts and suggestions on a solution are appreciated.

Jay
CompuMatter

**Comment by mustardamus** [comment]
Hmm, seems like there is some margin or padding. Try out the new version and see if the problem still exist. Closed in favor of the new version.
