### ISSUE TITLE
Drop down menu with pre-selected value

### ISSUE THREAD

**Issue by caseytrombley** [mustardamus/ketchup-plugin#36]
How do you tell Ketchup to work on a drop-down menu if there is a pre-selected option value? For example, is there a validation that says something like "require if the value is NOT this "select a state""?

**Comment by caseytrombley** [comment]
Actually figured this out now, I created a new validator and message, here is my validator:

$.fn.ketchup.validation('selectstate', function(element, value) {
  if(value == 'Select') return false;
  else return true;
});

Here is the message:

'selectstate':  'Must select a state.',

THANKS FOR MAKING THIS SO FLEXIBLE!

**Comment by hellokingdom** [comment]
Or in latest version this will error if select is first option.

.validation('select', 'Please make a selection', function(form, el, value, max) {
  return ($("option",el).index($("option:selected",el)) > 0) ? true : false;
}, function(form, el) {
  this.bindBrothers(form, el);
})
