### ISSUE TITLE
Problem with positioning ( in latest version )

### ISSUE THREAD

**Issue by Shoegoe** [mustardamus/ketchup-plugin#39]
Hi,
The initial positioning works fine, but in my layout , when i scroll the bubble sticks to the same place. this i presume is due to the positioning relative to the body.

a short version of the current layout would be

&lt;body scroll=&quot;no&quot;&gt;
&lt;form &gt;
&lt;div style=&#39;overflow-y:hidden;height:30px&#39;&gt;
some content 
&lt;/div&gt;
&lt;div style=&#39;position:relative;overflow-y:scroll&#39;&gt;
some more content
&lt;div&gt;
&lt;input type=&#39;text&#39; data-validate=&#39;validate(required, email)&#39; id=&#39;mail&#39;&gt;
&lt;input type=&#39;submit&#39;/&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/form&gt;
&lt;!--your bubble div comes here--&gt;
&lt;/body&gt;

Now, if the page uses similar layout, the plugin breaks.

**Comment by mustardamus** [comment]
Thats because the default position is absolute to the body and positioned on the field to validate. You can overwrite the createErrorContainer() to be appended after the field to validate and position it relatively.
