### ISSUE TITLE
horizontal position

### ISSUE THREAD

**Issue by regeda** [mustardamus/ketchup-plugin#4]
// ++ PATCH
  function changePosition (errorContainer, field, handler)
  {
    var fOffset = field.offset();

```
errorContainer[handler]({
  left: fOffset.left + field.width() - 10,
  top: fOffset.top - errorContainer.height()
});
```

  }
  // -- PATCH

  var initialPositionContainer = function(errorContainer, field) {
    changePosition(errorContainer, field, "css"); // ++ PATCH
  };

  var positionContainer = function(errorContainer, field) {
    changePosition(errorContainer, field, "animate"); // ++  PATCH
  };

**Comment by mustardamus** [comment]
Nice refactoring. Will change it in the next version.

**Comment by mustardamus** [comment]
Closed in favor of the new version.
