### ISSUE TITLE
Issue with validation of checkboxes

### ISSUE THREAD

**Issue by jlgoolsbee** [mustardamus/ketchup-plugin#40]
When validating checkboxes (like minselect), the other checkboxes in the group are only tagged for validation if they are siblings of the same parent element as the checkbox that the validation is tagged to.  This means that if say, for styling purposes each checkbox/label is wrapped in a div, the only checkbox that the validation will be applied to is the one which is tagged with the validation code.

**Comment by jlgoolsbee** [comment]
I did some digging; the issue appears to be in the "inputsWithNameNotSelf" helper, where index() is used to identify unique checkboxes (index only returns elements that have the same parent element).  To get around this, I replaced that line with a check on the ID of the checkboxes to do the filtering instead:

```
.helper('inputsWithNameNotSelf', function(form, el) {
    return this.inputsWithName(form, el).filter(function() {
        return ($(this).attr('id') != el.attr('id'));
    });
})
```

**Comment by mustardamus** [comment]
Right, that works too, but then the checkbox must have a ID. It is really a custom problem, ad Ketchup is there to be hacked :)
