### ISSUE TITLE
Need ability to validate an entry regardless of it being required...

### ISSUE THREAD

**Issue by jlgoolsbee** [mustardamus/ketchup-plugin#41]
There are some inputs on my form that are not required, but that could still benefit from being validated.  However, it appears that this is currently not possible.  The plugin treats any element that's not "tasty" as being invalid and prevents the form from being submitted, even if the input is not also marked as being required.

**Comment by jlgoolsbee** [comment]
I solved this locally by wrapping pretty much all the regex statements in "( ... )?".

**Comment by StrangeElement** [comment]
This definitely needs to be applied in validation.basic.js.

**Comment by mustardamus** [comment]
This can be solved easily in the new version via helpers and own validations :)
