### ISSUE TITLE
Latest version doesn't work in IE7 / IE6

### ISSUE THREAD

**Issue by hellokingdom** [mustardamus/ketchup-plugin#49]
Hey,

Been using the plugin for a year or so. Switched to latest version and found it didn't work with IE7/IE6.

Traced bug to:

switch(fullString[i]) {

returning nothing in IE. 

Fixed to:
switch(fullString.charAt(i)) {

Now it fully works.

**Comment by mustardamus** [comment]
Thanks! Fixed it.
