### ISSUE TITLE
Feature Request - Additional Events + Scenario's

### ISSUE THREAD

**Issue by cadriel** [mustardamus/ketchup-plugin#5]
Hi There,

I've been implementing your validator over the past couple of day's and have encountered a couple of quirks that are easy to resolve, and would enhance the product I think.

1/
The hideContainer and showContainer should pass the associated field through. This way, you can easily apply styles or animations to the field itself should you want to.

2/
Perhaps the addition classes that are added to a container based on success or fail. The reason being, we're implementing inline form validation - but want a visual representation of the field being correct as well as incorrect. So we don't want to hide the container, just change it. :) If a class was applied to the container indicating this - then we could determine how to present it based on this.

3/
Going on the above comment, perhaps it might be prudent to add a couple of events, like onSuccess and onFail?

Otherwise - cheer's for an easy to use validator! :)

**Comment by mustardamus** [comment]
1) Good idea.
2) Hmm You could already do that on the hideContainer callback. You don't need to hide it, set a class 'success' on the error-container, and remove it in the showContainer callback.
3) showContainer = error occurred, hideContainer = no errors May be better documented in future.

Thanks for your feedback.

**Comment by stevenp** [comment]
Along these lines, I've added "validateSuccess" and "validateFailure" custom events to the "squeeze" function so that I can use ketchup to validate forms that I'm using for AJAX only. I also have to bind a call to preventDefault to my form's success event to make that work. Being able to use ketchup out-of-the-box for AJAX form validation would be killer.

**Comment by mustardamus** [comment]
Events are still to come in the new version. Closed in favor of the new version.
