### ISSUE TITLE
Breaks in IE7

### ISSUE THREAD

**Issue by ohanesian** [mustardamus/ketchup-plugin#6]
Is this not a BIG issue?

**Comment by cadriel** [comment]
Not just IE7, 8 too. :(

**Comment by mustardamus** [comment]
Works in 8 for me. I know this is a big issue, I'll do some more careful cross-browser testing for the next version. Don't expect IE6 support though :).

**Comment by cadriel** [comment]
Actually - try this;

Run in IE8, with a doc mode of IE8 standards. It runs perfectly.

Now run in IE8, with a doc mode of IE7 standards. It now thinks everything is a success. :D

**Comment by cadriel** [comment]
After further investigation, it's your extractValidations function that is broken.

**Comment by mustardamus** [comment]
Thank you very much for pointing that out! I hate debugging in IE :)

**Comment by cadriel** [comment]
I've fixed this, and cut the function size to 9 or so lines.

Try this;

```
    var valStr = field.attr(options.validationAttribute);
    valStr = valStr.substr(valStr.indexOf(validate) + validate.length);
    valStr = valStr.substr(1, valStr.length - 2);
    validations = valStr.split(",")
    for(var i = 0; i < validations.length; i++) {
        validations[i] = jQuery.trim(validations[i]);
    }

    return validations;
```

**Comment by cadriel** [comment]
Oh - also - your custom trim function breaks in IE. I suggest using jQueries one instead, as per above.

**Comment by mustardamus** [comment]
You are the man!

**Comment by cadriel** [comment]
Oh - this also now makes it work in IE6.

I know it's probably not a priority - but it's worth trying to keep the codebase viable for IE6. I know our userbase is still quite high.

**Comment by Delcarta** [comment]
I know i'm probably being slow, but how to i set the page to IE8 Standards and apply the extraction validation fix?

**Comment by Delcarta** [comment]
applying the fix above made it not work in any browser

**Comment by cadriel** [comment]
How did you apply it? You need to retain the function - but replace all the code within the function with my code above. It was more or less posted as an example for the developer of Ketchup for a future release of his rather than users applying. However, in any case - it should work.

To debug with IE, go to the tools menu and click "Developer Tools". Then, in the Developer Tools window that's open - in the menu on the right you'll see two options, browser mode - and document mode. Use these to set different render types etc for testing.

**Comment by mustardamus** [comment]
Hey Delcarta,
I'll update/fix Ketchup with cadriel's code asap when I find the time. Maybe next weekend.

**Comment by neilmonroe** [comment]
Traced the IE issue down to how this browser handles strings. IE6 (maybe 7) do not treat strings as arrays of characters, so in the extractValidations() function when reading through the validations from the markup, the code "valStr[i]" will return "undefined". What has to be done to modify this code is just change it to "valStr.charAt(i)" and the validations will be read in properly. There is a second use of this at the end of this function in the "default" case of the switch statement.

**Comment by jcc2010** [comment]
I applied neil's patch, and it does work.  For IE6, I also needed to change the trim calls to jQuery.trim, and it works in IE6.  The display isn't that great though, but that can be fixed in the CSS.  I'll add a comment if I get a chance to fix the display issues.

**Comment by doho** [comment]
Just a suggestion: changing the two field.offset() calls to jQuery's .position() routine instead (in jquery.ketchup.js) solves the error div position problems in all the browsers I've tested (ie6, 7, 8; FF; Chrome).

**Comment by neilmonroe** [comment]
I actually did the same thing, doho, in custom error display code in the page that was displaying the errors. I needed the errors to appear a bit different than the standard chat-style bubbles since my form was a bit crammed together and had lots of overlapping errors.

**Comment by shirishmore** [comment]
The existing function extractValidations() can be used,we just need to add 
valStr = valStr.split("");
before the for loop starts,the rest function can be used as it is.Below is the code
function extractValidations(field) {
    var valStr = field.attr(options.validationAttribute);
    valStr = valStr.substr(valStr.indexOf(validate) + validate.length + 1);
    var validations = [];
    var tempStr = '';
    var openBrackets = 0;
    valStr = valStr.split("");
    for(var i = 0; i < valStr.length; i++) {

```
  switch(valStr[i]) {
    case ',':
      if(openBrackets) {
        tempStr += ',';
      } else {
        validations.push(trim(tempStr));
        tempStr = '';
      }
      break;
    case '(':
      tempStr += '(';
      openBrackets++;
      break;
    case ')':
      if(openBrackets) {
        tempStr += ')';
        openBrackets--;
      } else {
        validations.push(trim(tempStr));
      }
      break;
    default:
      tempStr += valStr[i];
  }
}

return validations;    
```

  }

**Comment by nums** [comment]
Shirish,

It works great on IE7 and IE6.

Thanks

**Comment by ido50** [comment]
Thanks Shirish, that fix saved me.

**Comment by Ragadeepthi** [comment]
Thank you Shirish!!! thats really great

**Comment by mustardamus** [comment]
The new version still needs to be tested on IE. Closed in favor of the new version.

**Comment by jeffbyrnes** [comment]
Still seems to be broken in IE7; form just submits, thinking everything is valid. Sadly, I can't see (in the current code) how to implement Shirish's fix.
