### ISSUE TITLE
Need 'optional field' behavior

### ISSUE THREAD

**Issue by FlyboyArt** [mustardamus/ketchup-plugin#9]
For example, I have a field that is optional for the user but if they type something in it, I want to check it to make sure it is a valid URL. If nothing has been entered then I just want the validation bypassed. If I just have validate(url) then if someone just clicks in the field, and moves away they get an error popup. There should be a way to allow this. Perhaps a flag on a field by field basis to not error on empty?

Thoughts???

**Comment by mustardamus** [comment]
You could do this with your own validation like:

```
$.fn.ketchup.validation('optionalurl', function(element, value) {
  return /url regex/.test(value) || value.length == 0
});
```
